revk: Fix build on 8266
1. WIFI_EVENT_HOME_CHANNEL_CHANGE does not exist on this platform
2. lwmqtt_connected() returns uint32_t, which is not 'long'. Fixed compile error:

error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' {aka 'unsigned int'} [-Werror=format=]

On ESP32 it also returns uint32_t, apparently compilation options differ

Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>